### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by research555** [bpluly/AccountActivity#2]
Hi, I love this extension and think its incredible you've made it. However I'm finding it tough to implement. Is it possible to perhaps include some examples or maybe walk me through the process? I'm trying to stream direct messages.

**Comment by bpluly** [comment]
I know it's a long wait. But there's a fragment of code that subscribes to all of a User's Account Activity including DMs, 
https://gist.github.com/bpluly/6618a32d5c80e3486d3e29c8de518fb4
